In [3]:
import yfinance as yf
import pandas as pd
import logging
from datetime import datetime
from typing import Union

from typing import Union

logging.basicConfig(level=logging.ERROR)
logger = logging.getLogger(__name__)

def get_raw_stockmarket_data(ticker_name: str="^GSPC", period: str="1y") -> Union[pd.DataFrame, None]:
    """
    Fetches stock market value for the last month.
    Parameters:c
    - ticker_name (str): symbol for stockmarket value, specified by the yfinance library.
    - period (str): period for which to fetch data. Default is 1 month.
    Returns:
    - pd.DataFrame | None
    """
    try:
        data = yf.Ticker(ticker_name).history(period = period)
        if data.empty:
            logger.info("No stock market data found for the ticker: %s", ticker_name)
            return None
        return data
    except Exception as e:
        logger.error(f"Error getting stock market data: %s", e)
        return None

def get_yearly_stockmarket_trend(stockmarket_data: pd.DataFrame) -> Union[pd.DataFrame, None]:
    """
    Converts the raw stockmarket pd.DataFrame into a pd.DataFrame that contains:
    - current data;
    - trend estimator showing if stock market is "Rising" or "Falling".
    Parameters:
    - stockmarket_data (dataframe).
    Returns:c
    - pd.DataFrame | None
    """
    try:
        df = stockmarket_data.reset_index()[['Close']].copy()
        df = df.rename(columns={'Close': 'stockmarket_value'})
        start_year = stockmarket_data.iloc[-1, 1]
        end_year = stockmarket_data.iloc[0, 1]
        if start_year > end_year:
            estimate = "Rising"
        elif start_year == end_year:
            estimate = "Stable"
        else:
            estimate = "Falling"
        date = datetime.now().date()
        stockmarket = pd.DataFrame({'date': [date], 'stockmarket': [estimate]})
        return stockmarket
    except Exception as e:
        logger.info("Error preprocessing stock market data: %s", e)
        return None

def get_montly_stockmarket_trend(stockmarket_data: pd.DataFrame) -> Union[pd.DataFrame, None]:
    """
    Converts the raw stockmarket pd.DataFrame into a pd.DataFrame that contains:
    - current data;
    - trend estimator showing if stock market is "Rising" or "Falling".
    Parameters:
    - stockmarket_data (dataframe).
    Returns:c
    - pd.DataFrame | None
    """
    try:
        df = stockmarket_data.reset_index()[['Close']].copy()
        df = df.rename(columns={'Close': 'stockmarket_value'})
        start_month = df.iloc[-25, 0]
        end_month = df.iloc[-1, 0]
        if start_month < end_month:
            estimate = "Rising"
        elif start_month == end_month:
            estimate = "Stable"
        else:
            estimate = "Falling"
        date = datetime.now().date()
        stockmarket = pd.DataFrame({'date': [date], 'stockmarket': [estimate]})
        return stockmarket
    except Exception as e:
        logger.info("Error preprocessing stock market data: %s", e)
        return None

def get_yearly_stockmarket_data_for_dashboard(stockmarket_data: pd.DataFrame) -> Union[pd.DataFrame, None]:
    """
    Converts the raw stockmarket pd.DataFrame into a pd.DataFrame that contains:
    - current data;
    - trend estimator showing if stock market is "Rising" or "Falling".
    Parameters:
    - stockmarket_data (dataframe).
    Returns:c
    - pd.DataFrame | None
    """
    try:
        df = stockmarket_data.reset_index()[['Date','Close']].copy()
        df = df.rename(columns={'Close': 'stockmarket_value', 'Date': 'date'})
        df['date'] = df['date'].dt.date
        return df
    except Exception as e:
        logger.info("Error preprocessing stock market data: %s", e)
        return None

In [4]:
raw = get_raw_stockmarket_data()
raw

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-10-25 00:00:00-04:00,5826.750000,5862.819824,5799.979980,5808.120117,3501280000,0.0,0.0
2024-10-28 00:00:00-04:00,5833.930176,5842.919922,5823.080078,5823.520020,3691280000,0.0,0.0
2024-10-29 00:00:00-04:00,5819.680176,5847.189941,5802.169922,5832.919922,3879100000,0.0,0.0
2024-10-30 00:00:00-04:00,5832.649902,5850.939941,5811.279785,5813.669922,3851120000,0.0,0.0
2024-10-31 00:00:00-04:00,5775.339844,5775.339844,5702.859863,5705.450195,4425660000,0.0,0.0
...,...,...,...,...,...,...,...
2025-10-20 00:00:00-04:00,6690.049805,6744.350098,6690.049805,6735.129883,4672170000,0.0,0.0
2025-10-21 00:00:00-04:00,6736.750000,6752.160156,6722.029785,6735.350098,5245020000,0.0,0.0
2025-10-22 00:00:00-04:00,6741.339844,6741.750000,6655.689941,6699.399902,5710010000,0.0,0.0
2025-10-23 00:00:00-04:00,6703.649902,6749.529785,6700.140137,6738.439941,5565750000,0.0,0.0
2025-10-24 00:00:00-04:00,6772.069824,6807.109863,6772.069824,6791.689941,5058220000,0.0,0.0

In [5]:
sm = get_yearly_stockmarket_trend(raw)
sm

         date stockmarket
0  2025-10-26      Rising

In [6]:
m = get_montly_stockmarket_trend(raw)
m

         date stockmarket
0  2025-10-26      Rising

In [7]:
d = get_yearly_stockmarket_data_for_dashboard(raw)
d

           date  stockmarket_value
0    2024-10-25        5808.120117
1    2024-10-28        5823.520020
2    2024-10-29        5832.919922
3    2024-10-30        5813.669922
4    2024-10-31        5705.450195
..          ...                ...
245  2025-10-20        6735.129883
246  2025-10-21        6735.350098
247  2025-10-22        6699.399902
248  2025-10-23        6738.439941
249  2025-10-24        6791.689941

[250 rows x 2 columns]

In [8]:
d.iloc[0]['stockmarket_value']

np.float64(5808.1201171875)